#!/bin/sh

# Script to load/unload aesd char driver

case "$1" in
    start)
        echo "Loading aesdchar module"
        aesdchar_load || exit 1
        ;;

    stop)
        echo "Unloading aesdchar module"
        aesdchar_unload
        ;;

    restart)
        echo "Restarting the LDD modules"
        $0 stop
        $0 start
        ;;

    *)
        echo "Usuage: $0 {start | stop | restart}"
        exit 1

esac

exit 0